### ISSUE TITLE
Slim down integration tests

### ISSUE THREAD

**Issue by carolynvs** [deislabs/porter#1079]
- [x] Move test-cli for terraform into porter-terraform
- [ ] Look into using KinD instead of aks (could run without creds)
- [x] ~Move azure plugin tests to azure plugin repo~ Carolyn dreamed this one up, azure plugin wasn't in porter's repo

**Comment by vdice** [comment]
@carolynvs `Move azure plugin tests to azure plugin repo`: which test(s) are these?

**Comment by carolynvs** [comment]
I thought that we had a test in porter that used the azure plugin, but I just searched the code and we don't. Updating the OP to remove that one.
