### ISSUE TITLE
Required steps to perform before publication [porter-kubernetes mixin]

### ISSUE THREAD

**Issue by MChorfa** [deislabs/porter#1239]
## Porter Kubernetes mixin extraction from the main porter project
A new Kubernetes mixin was created <https://github.com/deislabs/porter-kubernetes>. Now we need to follow this proposed process to make sure everything is working as intended. 

## Checklist:

- [x] Put in place (azure devops) CI to run  build/tests against PRs and publishing from main  or tag: https://github.com/deislabs/porter-kubernetes/issues/2
- [x] Make sure the main branch is stable/working as intended: https://github.com/deislabs/porter-kubernetes/issues/3
- [x] Cut release from main when it is ready: https://github.com/deislabs/porter-kubernetes/issues/4
- [x] Update any docs accordingly: https://github.com/deislabs/porter-kubernetes/issues/5
- [x] Set up the feed and create a PR to update the porter main feed: https://github.com/deislabs/porter-kubernetes/issues/6
- [x] Create a PR to add the `Kubernetes mixin` feed into porter-packages: https://github.com/deislabs/porter-kubernetes/issues/7
- [x] Remove the Kubernetes mixin code from the deislabs/porter main project and point to the new Kubernetes mixin package: https://github.com/deislabs/porter/issues/1240

**Comment by MChorfa** [comment]
All tasks completed 🎉 !

**Comment by vdice** [comment]
👏 Thank you @MChorfa !
