### ISSUE TITLE
Publish all assets to porter domains / orgs

### ISSUE THREAD

**Issue by carolynvs** [deislabs/porter#824]
- [x] Publish mixins and plugins to porter.sh instead of deislabs.io
- [x] Use front door instead of verizon CDN because the CDN has been giving us problems and we are bypassing it at all times at this point.
- [x] Publish our remaining example bundles to getporter on docker hub.
    - [x] Update/revisit example bundles https://github.com/deislabs/porter/issues/856
- [x] Publish our test bundles to getporterci too (make a new org) - see https://github.com/deislabs/porter/pull/857

**Comment by vdice** [comment]
Currently working on `Publish our remaining example bundles to getporter on docker hub.` and had a few Q's.

1. These example bundles are all the ones in the `examples` directory, correct?  Do we wish to publish any of the bundles in the `workshop` dir?  And/or from another location?

2. The current list of bundles in the `examples` dir is:

- aks-spring-music
- azure-ark
- azure-mysql-wordpress
- azure-tf-example
- exec-outputs
- gke-example
- kubernetes-mixin-example
- user-service-fabric-cli

Do we wish to continue maintaining/publishing all of these?  For instance, I know the `azure-ark` bundle is currently outdated (😬  still haven't gotten to https://github.com/deislabs/porter/issues/324).

The README in `examples` currently only mentions the top 3 in the list above, so we can add new entries depending on the final list.

**Comment by vdice** [comment]
Also, as I'm going through all of the bundles (examples, test) to update the org (`deislabs` -> `getporter` or `getporterci`), I've been eliminating the `invocationImage` section since we now have the logic to create the appropriately named invocation image based on `tag`.  Wanted to check in here to see if now is a good time to establish that precedent?  (Only keeping the updated `tag` field)

**Comment by jeremyrickard** [comment]
I think we should maybe limit the examples. The Ark example kind of points to having too many to make maintain.

**Comment by vdice** [comment]
> I think we should maybe limit the examples. The Ark example kind of points to having too many to make maintain.

Ok, created https://github.com/deislabs/porter/issues/856 that I can work on as a follow-up

**Comment by carolynvs** [comment]
I'm sorry for the slow replies! 😬 

> These example bundles are all the ones in the examples directory, correct? Do we wish to publish any of the bundles in the workshop dir? And/or from another location?

I was suggesting just the bundles in examples. I don't recommend publishing the workshop bundles.

> Do we wish to continue maintaining/publishing all of these? For instance, I know the azure-ark bundle is currently outdated

I agree with Jeremy that we should prune the examples to just the ones that we want to maintain. If something is out of date already, and we don't want to update it, let's leave it off. I would prefer to use the examples to demonstrate various aspects of porter, and not just "porter + app X".

**Comment by jeremyrickard** [comment]
> I would prefer to use the examples to demonstrate various aspects of porter, and not just "porter + app X".

I have a strong preference for this too.

**Comment by vdice** [comment]
Oops!  This can be closed now.
