### ISSUE TITLE
Meta: Package Discoverability

### ISSUE THREAD

**Issue by vdice** [deislabs/porter#909]
This issue tracks enhancements/refactors to get package discoverability (mixins, plugins) in a more ideal state.

- [x] General package search support: https://github.com/deislabs/porter/issues/906
- [x] Support Plugin search: https://github.com/deislabs/porter/issues/907
- [x] Decouple package directories from Porter CLI: https://github.com/deislabs/porter/issues/908
